### The most important Markdown shortcuts in Jupyter Lab

- shift/alt + enter - execute current cell and add another below
- ctrl + enter      - execute current cell
- a - inserts the code cell above
- b - inserts the code cell below
- x - cuts the selected cell
- c - copies the selected cell
- v - pastes the cell below
- double d - deletes the selected cell
- z - undo the cell deletion
- y - changes the cell type to Code,
- m - changes the cell type to Markdown
- ctrl + / - comment a line

In [1]:
a=5 # assign variable a to literal 3
print(a) # print a variable

5


In [ ]:
# we can also inspect the type of variables
a=3
print('a is of type',type(a))
b = 2.1
print('b is of type',type(b))
c = a/b
print('c is of type',type(c), 'and its value is',c)

a is of type <class 'int'>
b is of type <class 'float'>
c is of type <class 'float'> and its value is 1.4285714285714286
d is of type <class 'float'> and its value is 1.4285714285714286


In [ ]:
a = 4
b = 2
c = a/b
print("a is of type", type(a))
print("b is of type", type(b))
print("c is of type", type(c)) # division changes the type to float

a is of type <class 'int'>
b is of type <class 'int'>
c is of type <class 'float'>


In [ ]:
# you can also write it as given below using "f" 
# have the variables in {}

print(f"a is of type {type(a)}, b is of type {type(b)} and c is of {type(c)}")

a is of type <class 'int'>, b is of type <class 'int'> and c is of <class 'float'>


In [ ]:
a = [1,3,2,5,4,7,2,9]
print(a*3) # repeats the list a three times

a.index(5) # gives the index of the element

[1, 3, 2, 5, 4, 7, 2, 9, 1, 3, 2, 5, 4, 7, 2, 9, 1, 3, 2, 5, 4, 7, 2, 9]


3

In [ ]:
# shallow copy
# deep copy


In [ ]:
# a tuple is an ordered collection of values, are unchangeable/immutable, allow duplicates and can be indexed

a = (1,2,3,4,5)
print(a)
print(f"First element - {a[0]}, Last element - {a[-1]}")

(1, 2, 3, 4, 5)
First element - 1, Last element - 5


In [ ]:
# if you have to change a value in the tuple then change the tuple to a list, change the value and change it back to a tuple

a = (1,2,3,4,5)
a = list(a)
a[0] = 10
print(f"This is a list: {a}")

a = tuple(a)
print(f"This is a tuple: {a}")

This is a list: [10, 2, 3, 4, 5]
This is a tuple: (10, 2, 3, 4, 5)


In [ ]:
# a set is an unordered collection of values that are changeable and does NOT allow duplicates

a = {1,2,3,4,1,2,3}
print(f"This is a set: {a} \n")  # removes the duplicates

# you can't change values but you can add and remove entries from a set
a.add(6) # added new element
print(f"Added new element 6 to a: {a} \n")

a.remove(1)
print(f"Removed 1 from a: {a}")

This is a set: {1, 2, 3, 4} 

Added new element 6 to a: {1, 2, 3, 4, 6} 

Removed 1 from a: {2, 3, 4, 6}


In [ ]:
# a dictionaries are unordered, indexed and changeable/mutable

d = {"One":1, "Two":2, "Three":3}
print(f"Dictionary: {d} \n")
print(f"First element of dictionary: {d['One']} \n")         # note the brackets used to get an element of the dictionary d["One"]

d["Four"] = 4
print(f"Added a new element to the dictionary: {d}")

Dictionary: {'One': 1, 'Two': 2, 'Three': 3} 

First element of dictionary: 1 

Added a new element to the dictionary: {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4}


In [ ]:
print(*range(6))

0 1 2 3 4 5


In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(10):
    print(i, end="")      # print 0 to 9 in same line without space between the values

print()                   # new line
for i in range(-10, 10):  # loop from -10 to 9
    print(i, end=" ")     # print in same line with space between the values

print()                   # new line
for i in range(1, 20, 2): # Loop from 1 to 19 with gap/increment/jump of 2
    print(i, end=" ")     

print()                   # new line
for i in range(11, 10):   # will not print anything. Will not throw an error either. start needs to be smaller than 
    print(i, end =", ")   

0123456789
-10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9 
1 3 5 7 9 11 13 15 17 19 


In [ ]:
# we can convert a range to a list

print(list(range(0,10,2)))

[0, 2, 4, 6, 8]


In [ ]:
# "C:\Users\hp\Downloads\" you get path of the file from explorer with backslash "\"
# in jupyter notebook/lab we have to change the backslash to forward slash to read the file
# r stands for "raw" and will cause backslashes in the string to be interpreted as actual backslashes rather than special characters.

import pandas as pd
# df = pd.read_csv("C:/Users/hp/desktop/Important/quality.csv")                        # or
# df1 = pd.read_csv(r"C:\Users\hp\desktop\Important\quality.csv")                      # or
# df2 = pd.read_excel(r"C:\Users\hp\desktop\Important\Delhi_Pollution_data.xlsx")      # or
df3 = pd.read_excel("C:\\Users\\hp\\desktop\\Important\\Delhi_Pollution_data.xlsx")

In [ ]:
df3.head(1)

City       Date  PM2.5    PM10    NO    NO2    NOx    NH3    CO    SO2  \
0  Delhi 2020-07-01  54.01  128.66  6.33  21.05  16.81  29.06  0.97  11.15   

      O3  Benzene  Toluene  Xylene  AQI AQI_Bucket  
0  29.73     2.03    23.57    0.65  101   Moderate

In [ ]:
import os
os.getcwd() # this code will show you your current working directory
# os.chdir("path to desired directory")# changes the working directory

'C:\\Users\\hp\\Desktop\\Important'

In [ ]:
a = 123abc      # if we want to assign a string value to a variable then it needs to be in "" else it will throw an error
print(a)

SyntaxError: invalid syntax (3547514831.py, line 1)

In [ ]:
a = abc       # here python will look for a varible abc
print(a)

NameError: name 'abc' is not defined

In [ ]:
# convert a numner to a string

a = 123
a = str(a)
print("a:", a)
print(type(a))

a: 123
<class 'str'>


In [ ]:
# you cannot add a number to a string

a = "1"
b = 2
print(a+b)

TypeError: can only concatenate str (not "int") to str

In [ ]:
print(a+a) # "+" concatenates the strings
print(a*5) # repeats the string just like a list

11
11111


In [ ]:
a= 1
for i in range(6):
    a = a* i
print(a)

0


In [ ]:
# we can use == between a string and an integer

i='1'
if i==49:
    print(1)
else: 
    print(2)

2


In [ ]:
# cannot compare a string with a integer

i='2'
if i<1:
    print(1)
else: 
    print(2)

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
print("\")  # \ is an escape character and cannot be printed alone

SyntaxError: EOL while scanning string literal (94648274.py, line 1)

In [ ]:
import numpy as np
a = np.linspace(1,9,3) #  returns number spaces evenly w.r.t interval
print(a)

a = np.linspace(0,20,5) #  returns number spaces evenly w.r.t interval
print(a)


[1. 5. 9.]
[ 0.  5. 10. 15. 20.]


In [ ]:
vec= np.arange(10,20)
print(vec, "\n")

vec2=vec[np.arange(0,10,2)]      # prints elemnts with index 0,2,4,6,8
print(vec2, "\n")

vec2=vec[range(1,4)]             # prints elements with index 1,2,3 
print(vec2)

[10 11 12 13 14 15 16 17 18 19] 

[10 12 14 16 18] 

[11 12 13]


In [ ]:
a = pd.Series([1,2,3])
b = pd.Series([4,5,6])

print(pd.concat([a,b], axis=0, ignore_index=True),"\n")

print(pd.concat([a,b], axis=1, ignore_index=True))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64 

   0  1
0  1  4
1  2  5
2  3  6


In [ ]:
# save matrix to a file

mat1 = [np.arange(1,10).reshape(3,3)]
mat2 = [np.arange(11,20).reshape(3,3)]

np.save("mat1", mat1)                     # creates mat1.npy
np.savez('zipped_mat1', mat1=mat1, mat2=mat2)        # creates zipped_mat1.npz

In [ ]:
# load the saved matrix

saved_mat = np.load("mat1.npy")
print("Single array \n", saved_mat[0], "\n")

zipped_file = np.load("zipped_mat1.npz")
sorted(zipped_file.files)
print("Zipped arrays\n",zipped_file["mat1"], "\n\n", zipped_file["mat2"])


Single array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Zipped arrays
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]] 

 [[[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [ ]:
arr1 = [np.arange(1,10)]
np.savetxt('text_file_name.txt', arr1, delimiter=',')        # should be 1D or 2D array
mat_txt = np.loadtxt('text_file_name.txt', delimiter=',')
print(mat_txt)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
list1 = [1,2,3,4]
labels = ['first','second','third','fourth']
series1 = pd.Series(data=list1, index=labels)
print(series1)

first     1
second    2
third     3
fourth    4
dtype: int64


In [ ]:
d = {'a': 1, 'b': 2, 'c': 3}
series1 = pd.Series(data=d, index=['a', 'b', 'c'])
print(series1, "\n")
print("First element: ", series1["a"])                # accessing the first element of the series

a    1
b    2
c    3
dtype: int64 

First element:  1


In [ ]:
d = {'a': 1, 'b': 2, 'c': 3}
series1 = pd.Series(data=d, index=['x', 'y', 'z'])  # if creating series from a dictionary, the index should be same as the keys
series1

x   NaN
y   NaN
z   NaN
dtype: float64

In [ ]:
# addition of series

s1 = pd.Series([10,20,30])
s2 = pd.Series([40,50,60])
s3 = s1+s2
print(s3)

0    50
1    70
2    90
dtype: int64


In [ ]:
# we can combine series to create a dataframe using the concat function
# can combine dataframes too with concat

df = pd.concat([s1,s2],axis=1,keys=["First","Sec"])
df

First  Sec
0     10   40
1     20   50
2     30   60

In [ ]:
df = pd.DataFrame(np.array(np.arange(0,20).reshape(4,5)))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [ ]:
df.loc[[0,1,2],[0,2]]

0   2
0   0   2
1   5   7
2  10  12

In [ ]:
df[df>=10]

0     1     2     3     4
0   NaN   NaN   NaN   NaN   NaN
1   NaN   NaN   NaN   NaN   NaN
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
# add column to the dataframe

df[5] = [1,2,3,4]
df

0   1   2   3   4  5
0   0   1   2   3   4  1
1   5   6   7   8   9  2
2  10  11  12  13  14  3
3  15  16  17  18  19  4

In [ ]:
# delete a column from the dataframe
df = df.drop(1,axis=1)
df

0   2   3   4  5
0   0   2   3   4  1
1   5   7   8   9  2
2  10  12  13  14  3
3  15  17  18  19  4

In [ ]:
# or

df.drop(2,axis=1, inplace=True)
df

0   3   4  5
0   0   3   4  1
1   5   8   9  2
2  10  13  14  3
3  15  18  19  4

In [ ]:
# drop a row

df = df.drop(2,axis=0)
df

0   3   4  5
0   0   3   4  1
1   5   8   9  2
3  15  18  19  4

In [ ]:
#reset index of a dataframe

df = df.reset_index() # or df.reset_index(inplace=True)
df

index   0   3   4  5
0      0   0   3   4  1
1      1   5   8   9  2
2      3  15  18  19  4

In [ ]:
# set index using an array or a series

df = pd.DataFrame(np.array(np.arange(0,20).reshape(4,5)))
ind = np.array(["a","b","c","d"])
df = df.set_index(ind)
df

0   1   2   3   4
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19

In [ ]:
df1 = pd.DataFrame({"customer":['101','102','103','104'], 
                    'category': ['cat2','cat2','cat1','cat3'],
                    'important': ['yes','no','yes','yes'],
                    'sales': [123,52,214,663]},index=[0,1,2,3])

df2 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])

In [ ]:
df1

customer category important  sales
0      101     cat2       yes    123
1      102     cat2        no     52
2      103     cat1       yes    214
3      104     cat3       yes    663

In [ ]:
df2

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [ ]:
pd.concat([df1,df2],axis=0,sort=False)

customer category important  sales   color  distance
0      101     cat2       yes    123     NaN       NaN
1      102     cat2        no     52     NaN       NaN
2      103     cat1       yes    214     NaN       NaN
3      104     cat3       yes    663     NaN       NaN
4      101      NaN       NaN    123  yellow      12.0
5      103      NaN       NaN    214   green       9.0
6      104      NaN       NaN    663   green      44.0
7      105      NaN       NaN    331    blue      21.0

In [ ]:
pd.concat([df1,df2],axis=0,sort=True)

category   color customer  distance important  sales
0     cat2     NaN      101       NaN       yes    123
1     cat2     NaN      102       NaN        no     52
2     cat1     NaN      103       NaN       yes    214
3     cat3     NaN      104       NaN       yes    663
4      NaN  yellow      101      12.0       NaN    123
5      NaN   green      103       9.0       NaN    214
6      NaN   green      104      44.0       NaN    663
7      NaN    blue      105      21.0       NaN    331

In [ ]:
pd.concat([df1,df2],axis=1,sort=False)

customer category important  sales customer   color  distance  sales
0      101     cat2       yes  123.0      NaN     NaN       NaN    NaN
1      102     cat2        no   52.0      NaN     NaN       NaN    NaN
2      103     cat1       yes  214.0      NaN     NaN       NaN    NaN
3      104     cat3       yes  663.0      NaN     NaN       NaN    NaN
4      NaN      NaN       NaN    NaN      101  yellow      12.0  123.0
5      NaN      NaN       NaN    NaN      103   green       9.0  214.0
6      NaN      NaN       NaN    NaN      104   green      44.0  663.0
7      NaN      NaN       NaN    NaN      105    blue      21.0  331.0

### Merge and Join
- Merge combines dataframes using a column's values to identify common entries
- Join combines dataframes using the index to identify common entries

In [ ]:
# outer merge is union based on the column given

pd.merge(df1,df2,how='outer',on='customer') 

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow      12.0    123.0
1      102     cat2        no     52.0     NaN       NaN      NaN
2      103     cat1       yes    214.0   green       9.0    214.0
3      104     cat3       yes    663.0   green      44.0    663.0
4      105      NaN       NaN      NaN    blue      21.0    331.0

In [ ]:
pd.merge(df1,df2,how='inner',on='customer') # inner merge is intersection 

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow        12      123
1      103     cat1       yes      214   green         9      214
2      104     cat3       yes      663   green        44      663

In [ ]:
# left merge is just first on, but all columns ... right is second

pd.merge(df1,df2,how='left',on='customer') 

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow      12.0    123.0
1      102     cat2        no       52     NaN       NaN      NaN
2      103     cat1       yes      214   green       9.0    214.0
3      104     cat3       yes      663   green      44.0    663.0

In [ ]:
pd.merge(df1,df2,how='right',on='customer') 

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow        12      123
1      103     cat1       yes    214.0   green         9      214
2      104     cat3       yes    663.0   green        44      663
3      105      NaN       NaN      NaN    blue        21      331

In [ ]:
df9 = pd.DataFrame({'Q1': [101,102,103],
                    'Q2': [201,202,203]},
                   index=['I0','I1','I2'])

df10 = pd.DataFrame({'Q3': [301,302,303],
                    'Q4': [401,402,403]},
                   index=['I0','I2','I3'])

In [ ]:
df9

Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [ ]:
df10

Q3   Q4
I0  301  401
I2  302  402
I3  303  403

In [ ]:
# join behaves just like merge, except instead of using the values of one of the columns to combine data frames, it uses the index labels

df9.join(df10,how='right') # outer, inner, left, and right work the same as merge

Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

In [ ]:
# applies function len() on the entire column - gives length of the entries

df2["color"].apply(len)

4    6
5    5
6    5
7    4
Name: color, dtype: int64

In [ ]:
df2

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [ ]:
def profit(s):
    return s*0.5 

# applymap works on a pandas Dataframe where a function is applied to every element individually
df11 = df2[['distance','sales']]
df11.applymap(profit)

distance  sales
4       6.0   61.5
5       4.5  107.0
6      22.0  331.5
7      10.5  165.5

In [ ]:
def col_sum(co):
    return sum(co)

df11.apply(col_sum)

distance      86
sales       1331
dtype: int64

In [ ]:
# df11.applymap(col_sum) # here applymap gives error as col_sum works on the entire column whereas applymap is for every element in the dataframe

In [ ]:
df11["sales"].map('Sales is {}'.format)

4    Sales is 123
5    Sales is 214
6    Sales is 663
7    Sales is 331
Name: sales, dtype: object

In [ ]:
# similar to numpy arrays, we can also save and load dataframes to csv files, and also Excel files

df11.to_csv('df11.csv',index=True)
new_df = pd.read_csv('df11.csv',index_col=0)
new_df

distance  sales
4        12    123
5         9    214
6        44    663
7        21    331

In [ ]:
df11.to_excel('df11.xlsx',index=False,sheet_name='first sheet')
new_df = pd.read_excel('df11.xlsx',sheet_name='first sheet',index_col=1)
new_df

distance
sales          
123          12
214           9
663          44
331          21

In [ ]:
mat2 = np.zeros([2,2])
print(mat2)
mat3 = np.ones((3,3))
print('')
print(mat3)
mat4 = np.eye(3)
print('')
print(mat4)

[[0. 0.]
 [0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec6-vec5)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[2 2 2 2 2]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [ ]:
# we can do matrix multiplication

product = np.matmul(vec5,vec6)
print(product)

85


In [ ]:
# we can find the unique values in an array

vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [ ]:
a = np.array(np.arange(0,9).reshape(3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# accessing elements of an array

print(a[1][2])
print(a[1,2])
print(a[0:2,1:3])

5
5
[[1 2]
 [4 5]]


In [ ]:
b = a[0:2,1:3]
print(b,"\n")
b[:] = 7
print(b,"\n")
print(a,"\n")           # changes in b are reflected in a as well

[[1 2]
 [4 5]] 

[[7 7]
 [7 7]] 

[[0 7 7]
 [3 7 7]
 [6 7 8]] 



In [ ]:
a = np.array(np.arange(0,9).reshape(3,3))
print("Matrix a: \n",a,"\n")

b = a[0:2,1:3].copy()                      # creates a separate matrix 
print("Copied Matrix b: \n",b,"\n")
b[:] = 7
print("Changed Matrix b: \n",b,"\n")
print("Unaffected Matrix a: \n",a,"\n")           # changes in b are not reflected in a 

Matrix a: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Copied Matrix b: 
 [[1 2]
 [4 5]] 

Changed Matrix b: 
 [[7 7]
 [7 7]] 

Unaffected Matrix a: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 



In [ ]:
vec=np.array([2, 4, 22, 67, 30, 17, 40, 18])
print(vec)
vec=np.where(vec>25,2,vec)                      # this works only with arrays and not with lists
print(vec)

[ 2  4 22 67 30 17 40 18]
[ 2  4 22  2  2 17  2 18]


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("Quality.csv")

In [ ]:
#highlight cells in dataframe display
def light(val):
    color = "yellow" if val >0  else ""
    return 'background-color: {}'.format(color)

dataframe = df
df_info = pd.DataFrame(dataframe.isnull().sum(), columns=["Null_values"])
df_info["Data_types"] = dataframe.dtypes
df_info.style.applymap(light, subset=["Null_values"])

In [ ]:
# treat outliers

# treat outliers
col = ["Reviews","Installs","Price","Size"]
for i in col:
    q1 = np.percentile(df[i],25)
    q3 = np.percentile(df[i],75)
    iqr = q3-q1
    upper_limit = q3 + 1.5*iqr
    lower_limit = q1 - 1.5*iqrsns
    
    df[i]=df[i].apply(lambda x: upper_limit if x> upper_limit else x)
    df[i]=df[i].apply(lambda x: lower_limit if x< lower_limit else x)

NameError: name 'np' is not defined